### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by tuhuynh27** [huytd/ascii-d#5]
@huytd  Is there any pre-build file that I can download and just run on my Mac or any `INSTALL.md` for self-build guidelines?

Since I'm not a Rust user, it would be easier for me if there is a step-by-step `INSTALL.md`.

Thanks!

**Comment by huytd** [comment]
Since it's still too early for any sort of demo or pre-built binary right now, I intentionally omit the build instruction from README.md

But if you want to try it out, make sure you have installed a stable Rust (install via [rustup](https://rustup.rs/) is a good way), then clone the source code and run:

```
cargo run

or

make run
```

I will put together some detailed instructions (maybe in `INSTALL.md`) once I finished something that worth showing to the public :D

**Comment by tuhuynh27** [comment]
Cool, I was able to build it now, thanks

**Comment by unrealhoang** [comment]
```
cargo run --release
```
